name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run:
    name: CI
    strategy:
      matrix:
        os: [windows-2019]
        include:
          # - os: ubuntu-22.04
          #   packages: '[ "runtime", "cudart", "cudart-dev", "nvrtc", "nvrtc-dev" ]'
          - os: windows-latest
            packages: '["nvrtc", "nvrtc_dev", "cudart"]'
          # Either the waiting queue for FreeBSD is very long, or it is not available.
          # - os: freebsd-latest
        ocaml-compiler:
          # - 4.13.x
          # - 5.0.x
          - 5.3.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: Jimver/cuda-toolkit@v0.2.22
      id: cuda-toolkit
      with:
        method: network
        sub-packages: ${{ matrix.packages }}
    - name: Set PATH for Windows
      # This is needed specifically for Windows CI, but should not hurt on other platforms.
      if: matrix.os == 'windows-latest' || matrix.os == 'windows-2019'
      run:
        echo "PATH=$CUDA_PATH\bin;$PATH" >> $GITHUB_ENV
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        dune-cache: true
        allow-prerelease-opam: true
    - run: opam pin -n .
    - run: opam install . --deps-only --with-test --with-doc
    - run: opam exec -- dune build
    - run: opam exec -- dune test test_no_device
