name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run:
    name: CI
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-latest]
        include:
          - os: ubuntu-22.04
            packages: '[ "runtime", "cudart", "cudart-dev", "nvrtc", "nvrtc-dev" ]'
          - os: windows-latest
            packages: '["nvrtc", "nvrtc_dev", "cudart"]'
        ocaml-compiler:
          - 4.13.x
          - 5.0.x
          - 5.3.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: Jimver/cuda-toolkit@v0.2.22
      id: cuda-toolkit
      with:
        method: network
        sub-packages: ${{ matrix.packages }}
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        dune-cache: true
        allow-prerelease-opam: true
    - run: opam pin -n .
    - run: opam install . --deps-only --with-test --with-doc
    - run: opam exec -- dune build
    - run: opam exec -- dune test test_no_device
