name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run:
    name: Build
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          - ubuntu-20.04
          # - windows-latest
          # - windows-2019
          # Either the waiting queue for FreeBSD is very long, or it is not available.
          # - freebsd-latest
        ocaml-compiler:
          - 5.1.x
          # - 5.2.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: Jimver/cuda-toolkit@v0.2.15
      id: cuda-toolkit
      with:
        method: network
        sub-packages: '[ "cudart", "cudart-dev", "drivers_520.61.05", "nvrtc", "nvrtc-dev"]'
      #   cuda: '12.4.1'
    - uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        dune-cache: true
        allow-prerelease-opam: true
    - run: opam pin -n .
    - run: opam depext -yt cudajit
    - run: opam install . --deps-only --with-test --with-doc
    - run: opam exec -- dune build
    - run: opam exec -- dune test test_no_device
