name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run:
    name: Build
    strategy:
      matrix:
        os:
          # - ubuntu-latest
          # - ubuntu-24.04
          # - ubuntu-22.04
          - windows-2022
          # - windows-2019
          # Either the waiting queue for FreeBSD is very long, or it is not available.
          # - freebsd-latest
        ocaml-compiler:
          # - 4.13.x
          - 5.3.x
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: Jimver/cuda-toolkit@v0.2.22
      id: cuda-toolkit
      with:
        cuda: 12.8.1
        method: network
        sub-packages: '[ "cudart", "cudart-dev", "runtime", "nvrtc", "nvrtc-dev" ]'
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
        dune-cache: true
        allow-prerelease-opam: true
    - run: opam pin -n .
    - run: opam depext -yt cudajit
    - run: opam install . --deps-only --with-test --with-doc
    - run: opam exec -- dune build
    - run: opam exec -- dune test test_no_device
