name: github pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment

jobs:
  deploy:
    # Avoid Ubuntu 24.04, see: https://github.com/ocaml/opam/issues/5968
    runs-on: ubuntu-22.04

    permissions:
      contents: 'read'
      id-token: 'write'
      pages: 'write'

    steps:
      - uses: actions/checkout@main

      - uses: Jimver/cuda-toolkit@v0.2.22
        id: cuda-toolkit
        with:
          method: network
          sub-packages: '[ "cudart", "cudart-dev", "nvrtc", "nvrtc-dev" ]'

      - name: Cache opam
        id: cache-opam
        uses: actions/cache@v4
        with:
          path: ~/.opam
          key: opam-ubuntu-22.04-5.2.0

      - uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '5.2.0'

      - name: Pin
        run: opam pin -n .

      - name: Depext
        run: opam depext -yt ocannl_npy arrayjit neural_nets_lib

      - name: Deps
        run: opam install -d . --deps-only

      - name: Build
        run: opam exec -- dune build @doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/default/_doc/_html/
          destination_dir: docs
          enable_jekyll: true
